### PR TITLE
Stringbuilder using fleunt interface

### LINKED ISSUE #37: Implement string concatenation with fluent syntax

### PR DESCRIPTION
**Pull request by jozefchmelar**
Implemented #37.  I used code by @Barteling  he posted on his blog here https://www.plccoder.com/fluent-code/
 The only difference is that  the `Reset` method is called `Clear` so it's the same as it is in C#. 

I'm not really sure whether TcoCore is the correct location for this class...I'll let this open for a discussion. 

image

### CODE REVIEW

**Comment by PTKu** [comment]
@jozefchmelar Unit tests? 😄 ?

**Review by PTKu — CHANGES_REQUESTED** [review]
Unit tests pls

**Comment by jozefchmelar** [comment]
Yeah, I thought that SB is too simple for a unit test
...turns out I made a mistake while implementing it 🙈

Hope you like it! :)

**Review by PTKu — APPROVED** [review]

**Comment by PTKu** [comment]
Maybe we should make something 'static' that would hold such helper-functions. Was thinking about a public PRG/GVL, but may be better to create something in the ```context```, to prevent concurrency and race conditions from different plc tasks...

**Comment by Barteling** [comment]
> Maybe we should make something 'static' that would hold such helper-functions. Was thinking about a public PRG/GVL, but may be better to create something in the `context`, to prevent concurrency and race conditions from different plc tasks...

Static code  is sometimes use full for very small/simple methods, but when they grow bigger/more advanced your code testability declines. As you always depend on the static method and cannot mock it.
I have this problem often with static extension methods in c#. It always sounds as a good idea but the testability is a problem.

**Review by Barteling — APPROVED** [review]

**Comment by PTKu** [comment]
> > Maybe we should make something 'static' that would hold such helper-functions. Was thinking about a public PRG/GVL, but may be better to create something in the `context`, to prevent concurrency and race conditions from different plc tasks...
> 
> Static code is sometimes use full for very small/simple methods, but when they grow bigger/more advanced your code testability declines. As you always depend on the static method and cannot mock it.
> I have this problem often with static extension methods in c#. It always sounds as a good idea but the testability is a problem.

Agreed... as I am thinking about it there are also other reasons for which it is a suboptimal idea... anyways maybe static is not the best denominator of what I had in mind... it is more something along the lines of a singleton in a given context.... 

The only question before merging... do we keep StringBuilder in TcoCore or we want to have it somewhere else... if this PR gets another review approval, I will merge it as it is

**Review by PTKu — APPROVED** [review]

**Pull request merged**
